### ISSUE TITLE
Exception("Can't get User Info List")

### ISSUE THREAD

**Issue by NunoSequeiraVSB** [jasonrollins/shareplum#5]
Hello I'm getting the error Exception("Can't get User Info List") when trying to access a site

**Comment by jasonrollins** [comment]
I need to add a better catch for this failure.  I've seen it when the user credentials are not correct for the site.  The library pulls the user info first and if it can't it fails in this very poorly worded way.  I don't know how your username and password should be presented to the SharePoint server but make sure you are using NTLM if you need to be and you possibly need to put your username as "DOMAIN\\Username" instead of just "Username"  Let me know if that resolves your issue.  I'll leave this issue open as a reminder that I need to do a better job of verifying the user credentials prior to doing anything else.

**Comment by NunoSequeiraVSB** [comment]
I used as indicated with the domain and the error no longer occurs
The user needs to have access to the user's info list
Thanks.

**Comment by pedro-cf** [comment]
how can one find their domain name ?
