### ISSUE TITLE
Unable to get items from large list using GetListItems()

### ISSUE THREAD

**Issue by lanceteo** [jasonrollins/shareplum#63]
Able to use GetListItems() for list less than 5000 items, but when used on list with 14,375 items, it returned a response <Response [500]> rather than a dataframe of the items.

Tried using huge_tree=True, but still does not work.

My code below:
site = Site(site_url, authcookie=authcookie, huge_tree=True)
sp = site.List(list_name)
sp_item = sp.GetListItems()

**Comment by jasonrollins** [comment]
Can you try it with a  rowlimit=10, like this sp_item = sp.GetListItems(
rowlimit=10)?

**Comment by lanceteo** [comment]
Setting rowlimit=10 works. rowlimit=5000 works as well. But anything beyond 5000 will only gives a response <Response [500]>.

**Comment by jasonrollins** [comment]
Is it possible that the server is refusing the request and that it isn't
related to SharePlum?

**Comment by travisg06** [comment]
I'm having the same problem, and it's definitely with SharePlum.

So my list has 220,000+ records.  My query is setup just like the documentation says, but here's the problem.  Let's say this is my setup:

`fields = ['Title', 'SQLUpdate']
query = {'Where': [('Eq', 'SQLUpdate', 'Yes')]}
sp_data = sp_list.GetListItems(fields=fields, query=query, rowlimit=5000)`

If my query returns less than 5000 items, there's absolutely no problem, works perfectly.  However, if I have more than 5000 items where SQLUpdate = "Yes", then even though I have rowlimit=5000 in my call, it does not respect the limit, and instead gives me the 500 server error which I've drilled down to list view threshold.

Now, here's the thing, if I remove query=query from the call, then it respects the rowlimit=5000 and it returns the first 5000 records.  So the issue here is that using a query and a rowlimit together is not working.

**Comment by jasonrollins** [comment]
SharePlum adds a query if you don't provide a viewname.  So if that works, then it isn't specifically the addition of the query parameter.  My you could see if providing a viewname changes things.  What version of SharePoint are you using?  Looking over the code, I can't see how query and rowlimit should affect each other.

**Comment by travisg06** [comment]
Adding viewname='All Items' did not change anything.  Still getting a 500 server error for exceeding list view threshold even when rowlimit=5000 is applied.  Adding a query along with rowlimit breaks the rowlimit to where it's not getting applied, which is forcing it to go over list view threshold.  If I simply remove query=query, then it works and returns the first 5000 items, but that's not how it should work, at least in my opinion.  It should take my query, and then from there if my query has more than 5000 items, it should limit the call to 5000 items and not exceed list view threshold.

Or it should make use of next tokens and recursively call the list in batches of 5000.

Here's a full breakdown of queries and results:

```
query = {'Where': [('Eq', 'SQLUpdate', 'Yes')]}
sp_data = sp_list.GetListItems(viewname='All Items', query=query, rowlimit=5000)
```
 **FAILS** - Query and RowLimit are not working together.

```
query = {'Where': [('Eq', 'SQLUpdate', 'Yes')]}
sp_data = sp_list.GetListItems(query=query, rowlimit=5000)
```
 **FAILS** - Query and RowLimit are not working together.

```
query = {'Where': [('Eq', 'SQLUpdate', 'Yes')]}
sp_data = sp_list.GetListItems(viewname='All Items', rowlimit=5000)
```
**WORKS** - but does not query the items for the result set I want because it just returns the first 5000 items.

**Comment by travisg06** [comment]
Is this something that is going to be looked into?

**Comment by jasonrollins** [comment]
Yeah sorry.  I haven't had a chance to try it yet.  Can you confirm if you
are using SharePoint 365?

**Comment by jasonrollins** [comment]
Can you confirm if this is for a newer SharePoint? 2016 or greater?  I'd like to move all issues for newer versions of SharePoint to SharePlum2.

**Comment by lanceteo** [comment]
@jasonrollins Mine is on SharePoint Online/365. By the way, is there a SharePlum2 already?

**Comment by lanceteo** [comment]
@jasonrollins Nevermind. I saw SharePlum2.

**Comment by travisg06** [comment]
@jasonrollins for me this is on SharePoint 2013 on-premises

**Comment by jasonrollins** [comment]
So I've done some research on this and I believe this is a limitation built into SharePoint.  It looks like you can increase the 5000 row limit if you have access to do that.  If you google "sharepoint 5000 item limit" you'll find a lot of articles that discuss possible solutions.  I'm going to go ahead and close this issue, because there really isn't anything SharePlum can do to get around this.
