### ISSUE TITLE
Possible to update items without changing modified info?

### ISSUE THREAD

**Issue by ejyoung82** [jasonrollins/shareplum#7]
Hello, I'd like to be able to update items in a list without changing the modified date/user.  Is this possible?  My current projects using shareplum run on a regular basis and we lose visibility on who modified an item as it changes to myself upon each run.

**Comment by jasonrollins** [comment]
I don't believe it's possible to change the modified date/user fields.  I'll have to look into it, but it's my understanding that those are generated on the server automatically.  What I would suggest that you do if you need to retain this info is to have two more columns added and copy the modified date/user fields when you read the list.  Then, if you update that row just write the copied info into the new modified date/user fields.

**Comment by ejyoung82** [comment]
Thanks for the reply Jason.  I wasn't sure if this is something that could
be done but wanted to check.  I thought about doing what you suggested but
it seems that once I'm the user listed in the modified field that the next
time the scheduled query runs I'd be copying my info to the new columns.  I
set up a workflow that copies that user that modified an item to a new
column as long as it isn't me which should work okay (I can always manually
edit the user to myself if I make an actual change to an item).  I'm hoping
I can retain the date information in a similar fashion but have not found a
solution yet.

Also, thanks for Shareplum!  It has been a great help as we start using
SharePoint sites more and more.

-Erik

**Comment by ejyoung82** [comment]
Actually, I figured out a workflow that will work to keep the date.  Not
sure why I didn't think of it before but I'm basically using the same set
up as keeping the user info - as long as it isn't modified by me.  This
should work for now.  Thanks again.

**Comment by jasonrollins** [comment]
Yes this is the solution I use myself.  Also, because I'm the only person running the scripts I can check if I am the last person that edited the row and make a decision to update the row based on that.

A situation where I found this to come up is when you are syncing a SharePoint list to a database and you need to decide how to remove items to match the database.  I had a situation where I needed to maintain rows that were manually entered but remove an items that were automatically added by my SharePoint script.  So when I did a comparison between the SharePoint list and database I would create a list of IDs to be removed and then filter out the ones that were not created by me. 

Do you use any of the ListDict methods?  I just realized I never documented that.  It's very useful if you are trying to keep a SharePoint list in sync with something else.
